#!/bin/bash
for ip in {131..169};
  do RESULT=`snmpwalk -v1 -c public X.X.X.$ip -On .1.3.6.1.4.1.1718.3.1.6.0 2>/dev/null | awk '{print $4}';
#echo "RESULT=$RESULT"
[[ $RESULT -gt 0 ]] && TOTAL=`echo$(($TOTAL + $RESULT))`
#echo "TOTAL=$TOTAL"
done
dt=`date '+%d/%m/%Y\n%H:%M:%S'`
echo -e "$TOTAL total watts\n$dt"
